import json
import logging
import os

from dotenv import load_dotenv

load_dotenv()


DATABASE_CONNECTION_STRING = os.environ["DATABASE_CONNECTION_STRING"]
LOGGING_LEVEL = logging.DEBUG

# Twilio settings
API_URL = os.environ["API_URL"]
TWILIO_ACCOUNT_SID = os.environ["TWILIO_ACCOUNT_SID"]
TWILIO_AUTH_TOKEN = os.environ["TWILIO_AUTH_TOKEN"]
TWILIO_PHONE_NUMBER = os.environ["TWILIO_PHONE_NUMBER"]


# Azure Service Bus settings
AZURE_SERVICEBUS_CONNECTION_STRING = os.environ["AZURE_SERVICEBUS_CONNECTION_STRING"]
AZURE_SERVICEBUS_QUEUE_NAME = os.environ["AZURE_SERVICEBUS_QUEUE_NAME"]

# Azure Blob Storage settings
AZURE_STORAGE_CONNECTION_STRING = os.environ["AZURE_STORAGE_CONNECTION_STRING"]
AZURE_STORAGE_ACCOUNT_KEY = os.environ["AZURE_STORAGE_ACCOUNT_KEY"]
AZURE_BLOB_CONTAINER_NAME = os.environ["AZURE_BLOB_CONTAINER_NAME"]

# Redis settings
REDIS_CONNECTION_STRINGS = json.loads(os.environ["REDIS_CONNECTION_STRINGS"])
REDIS_PORT = int(os.environ["REDIS_PORT"])
REDIS_LOCK_TIMEOUT_MS = int(os.environ["REDIS_LOCK_TIMEOUT_MS"])  # 1 minute
